fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

qualium_telus_votacion_homepage:
    pattern:  /
    defaults: { _controller: QualiumTelusVotacionBundle:Default:index }

reporte_visitas:
    pattern: /report/visitors/create
    defaults: { _controller: QualiumTelusVotacionBundle:Reportes:visitors }
    
generar_reporte_visitas:
    pattern: /report/visitors/execute/{days}
    defaults: { _controller: QualiumTelusVotacionBundle:Reportes:generateVisitorReports }
    
estisticas_votos:
    pattern: /admin/statistic/votes
    defaults: { _controller: QualiumTelusVotacionBundle:Estadisticas:votos }