<?php

namespace Qualium\Telus\VotacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ComitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComitesRepository extends EntityRepository
{
}
